---
AWSTemplateFormatVersion: 2010-09-09

Description: AWS CloudFormation for LAMP stack for MasterBuilder III by Ivo Janssen (jansseni@) 

Metadata:

  Authors:
    Description: Ivo Janssen (jansseni@amazon.com)
  License:
    Description: 'Inspired from https://github.com/aws-samples/aws-refarch-wordpress'

  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: General AWS
      Parameters:
        - EC2KeyName
        - SshAccessCidr
    - Label:
        default: Network settings
      Parameters:
        - VpcCidr
        - AvailabilityZones
        - PublicSubnetCidr
        - WebSubnetCidr0
        - WebSubnetCidr1
        - DBSubnetCidr0
        - DBSubnetCidr1
    - Label:
        default: Database settings
      Parameters:
        - DBName
        - DBUsername
        - DBPassword
    ParameterLabels:
      SshAccessCidr: 
        default: SSH Access CIDR
      EC2KeyName:
        default: EC2 Key Pair
      VpcCidr: 
        default: VPC CIDR
      AvailabilityZones:
        default: Availability Zones
      WebSubnetCidr0:
        default: Public subnet for bastion/nat gateways
      WebSubnetCidr0:
        default: Web subnet AZ1
      WebSubnetCidr1:
        default: Web subnet AZ2
      DBSubnetCidr0:
        default: Database subnet AZ1
      DBSubnetCidr1:
        default: Database subnet AZ2
      DBName:
        default: Database name
      DBUsername:
        default: Database username
      DBPassword:
        default: Database password



Parameters:
  VpcCidr:
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.31.0.0/16
    Description: CIDR block for the VPC
    Type: String
  AvailabilityZones:
    Description: List of Availability Zones to use for the subnets in the VPC. SELECT AT LEAST TWO AZ's!
    Type: List<AWS::EC2::AvailabilityZone::Name>
    MinLength: 1
  PublicSubnetCidr:
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.31.1.0/24
    Description: CIDR block for public subnet located in Availability Zone 1
    Type: String
  WebSubnetCidr0:
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.31.101.0/24
    Description: CIDR block for web subnet 1 located in Availability Zone 1
    Type: String
  WebSubnetCidr1:
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.31.102.0/24
    Description: CIDR block for web subnet 2 located in Availability Zone 2
    Type: String
  DBSubnetCidr0:
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.31.201.0/24
    Description: CIDR block for database subnet 1 located in Availability Zone 1
    Type: String
  DBSubnetCidr1:
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.31.202.0/24
    Description: CIDR block for database subnet 2 located in Availability Zone 2
    Type: String

  SshAccessCidr:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    Description: The CIDR IP range that is permitted to SSH to bastion instance. Note - a value of 0.0.0.0/0 will allow access from ANY IP address.
    Type: String
    Default: 0.0.0.0/0
  EC2KeyName:
    ConstraintDescription: Must be letters (upper or lower), numbers, and special characters.
    Description: Name of an EC2 KeyPair. Your bastion & Web instances will launch with this KeyPair.
    Type: AWS::EC2::KeyPair::KeyName
    MinLength: 1





Resources:

  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Join [ '', [ 'VPC/', !Ref 'AWS::StackName' ] ]

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 0, !Ref AvailabilityZones ]
      CidrBlock: !Ref PublicSubnetCidr
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Join [ '', [ 'PublicSubnet0/', !Ref 'AWS::StackName' ] ]
        - Key: SubnetType
          Value: Public
      VpcId: !Ref VPC
  WebSubnet0:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 0, !Ref AvailabilityZones ]
      CidrBlock: !Ref WebSubnetCidr0
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Join [ '', [ 'WebSubnet0/', !Ref 'AWS::StackName' ] ]
        - Key: SubnetType
          Value: Private
      VpcId: !Ref VPC
  WebSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 0, !Ref AvailabilityZones ]
      CidrBlock: !Ref WebSubnetCidr1
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Join [ '', [ 'WebSubnet1/', !Ref 'AWS::StackName' ] ]
        - Key: SubnetType
          Value: Private
      VpcId: !Ref VPC
  DBSubnet0:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 0, !Ref AvailabilityZones ]
      CidrBlock: !Ref DBSubnetCidr0
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Join [ '', [ 'DBSubnet0/', !Ref 'AWS::StackName' ] ]
        - Key: SubnetType
          Value: Private
      VpcId: !Ref VPC
  DBSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 0, !Ref AvailabilityZones ]
      CidrBlock: !Ref DBSubnetCidr1
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Join [ '', [ 'DBSubnet1/', !Ref 'AWS::StackName' ] ]
        - Key: SubnetType
          Value: Private
      VpcId: !Ref VPC

  BastionSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Join [ '', [ 'Bastion-SG/', !Ref 'AWS::StackName' ] ]
      GroupDescription: Security group for Bastion instances
      Tags:
        - Key: Name
          Value: !Join [ '', [ 'Bastion-SG/', !Ref 'AWS::StackName' ] ]
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref SshAccessCidr
      VpcId:
        !Ref VPC      
  DatabaseSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Join [ '', [ 'DB-SG/', !Ref 'AWS::StackName' ] ]
      GroupDescription: Security group for Amazon RDS cluster
      Tags:
        - Key: Name
          Value: !Join [ '', [ 'DB-SG/', !Ref 'AWS::StackName' ] ]
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !Ref WebSecurityGroup
      VpcId:
        !Ref VPC
  WebSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Join [ '', [ 'Web-SG/', !Ref 'AWS::StackName' ] ]
      GroupDescription: Security group for web instances
      Tags:
        - Key: Name
          Value: !Join [ '', [ 'Web-SG/', !Ref 'AWS::StackName' ] ]
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !Ref PublicAlbSecurityGroup
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          SourceSecurityGroupId: !Ref PublicAlbSecurityGroup
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          SourceSecurityGroupId: !Ref BastionSecurityGroup
      VpcId:
        !Ref VPC     
  PublicAlbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Join [ '', [ 'ALB-SG/', !Ref 'AWS::StackName' ] ]
      GroupDescription: Security group for ALB
      Tags:
        - Key: Name
          Value: !Join [ '', [ 'ALB-SG/', !Ref 'AWS::StackName' ] ]
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      VpcId:
        !Ref VPC           
        



Outputs:

  StackStatus:
    Description: Master Stack Status
    Value: !Join [ '', [ 'Stack created in region: ', !Ref 'AWS::Region' ] ]
  VPCCIDR:
    Description: VPC CIDR
    Value: !GetAtt [ VPC, CidrBlock]


